name: "Publish to CUE Registry"
on:
  push:
    tags:
      - "v*"

jobs:
  publish:
    runs-on: ubuntu-latest
    permissions:
      contents: read
    steps:
      - name: Checkout
        uses: actions/checkout@34e114876b0b11c390a56381ad16ebd13914f8d5 # v4.3.1
        with:
          fetch-depth: 0
          persist-credentials: false
      - name: Setup CUE
        uses: cue-lang/setup-cue@a93fa358375740cd8b0078f76355512b9208acb1 # v1.0.1
        with:
          version: "v0.17.0"
      - name: Login to CUE Central Registry
        run: cue login --token=${{ secrets.CUE_REG_TOKEN }}
      - name: Publish module
        env:
          REF_NAME: ${{ github.ref_name }}
        run: cue mod publish "$REF_NAME"
